apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.DOCKER_REGISTRY}}/hangchan/dns-over-tls:{{.VERSION}}"
  artifacts:
  - imageName: changeme
    workspace: .
    docker: {}
  local: {}
deploy:
  kubectl:
    manifests:
profiles:
- name: dev
  build:
    tagPolicy:
      envTemplate:
        template: "{{.DOCKER_REGISTRY}}/hangchan/dns-over-tls:{{.DIGEST_HEX}}"
    artifacts:
    - docker: {}
    local: {}
  deploy:
    helm:
      releases:
      - name: dns-over-tls
        chartPath: charts/dns-over-tls
        setValueTemplates:
          image.repository: "{{.DOCKER_REGISTRY}}/hangchan/dns-over-tls"
          image.tag: "{{.DIGEST_HEX}}"
